//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "checklists")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::checklist_steps::Entity")]
    ChecklistSteps,
    #[sea_orm(has_many = "super::inventory_item_kinds::Entity")]
    InventoryItemKinds,
    #[sea_orm(has_many = "super::inventory_items::Entity")]
    InventoryItems,
}

impl Related<super::checklist_steps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChecklistSteps.def()
    }
}

impl Related<super::inventory_item_kinds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemKinds.def()
    }
}

impl Related<super::inventory_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItems.def()
    }
}
