//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "executed_checklist_steps")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub position: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub executed_checklist_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::executed_checklists::Entity",
        from = "Column::ExecutedChecklistId",
        to = "super::executed_checklists::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ExecutedChecklists,
    #[sea_orm(has_many = "super::inventory_item_check_steps::Entity")]
    InventoryItemCheckSteps,
}

impl Related<super::executed_checklists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExecutedChecklists.def()
    }
}

impl Related<super::inventory_item_check_steps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemCheckSteps.def()
    }
}
