//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "executed_checklists")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::executed_checklist_steps::Entity")]
    ExecutedChecklistSteps,
    #[sea_orm(has_many = "super::inventory_item_checks::Entity")]
    InventoryItemChecks,
}

impl Related<super::executed_checklist_steps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExecutedChecklistSteps.def()
    }
}

impl Related<super::inventory_item_checks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemChecks.def()
    }
}
