//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "expiries")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub code: String,
    pub sqlite_modifier: String,
    pub sqlite_num_of_modifier: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::inventory_item_kinds::Entity")]
    InventoryItemKinds,
}

impl Related<super::inventory_item_kinds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemKinds.def()
    }
}
