//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inventory_item_kind_metadata_fields")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub position: i32,
    pub inventory_item_kind_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::inventory_item_metadata_values::Entity")]
    InventoryItemMetadataValues,
    #[sea_orm(
        belongs_to = "super::inventory_item_kinds::Entity",
        from = "Column::InventoryItemKindId",
        to = "super::inventory_item_kinds::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    InventoryItemKinds,
}

impl Related<super::inventory_item_kinds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemKinds.def()
    }
}

impl Related<super::inventory_item_metadata_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemMetadataValues.def()
    }
}
