//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inventory_item_metadata_values")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub value: String,
    pub inventory_item_id: i32,
    pub inventory_item_kind_metadata_field_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::inventory_item_kind_metadata_fields::Entity",
        from = "Column::InventoryItemKindMetadataFieldId",
        to = "super::inventory_item_kind_metadata_fields::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    InventoryItemKindMetadataFields,
    #[sea_orm(
        belongs_to = "super::inventory_items::Entity",
        from = "Column::InventoryItemId",
        to = "super::inventory_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    InventoryItems,
}

impl Related<super::inventory_item_kind_metadata_fields::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemKindMetadataFields.def()
    }
}

impl Related<super::inventory_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItems.def()
    }
}
