//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inventory_item_checks")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub finished: bool,
    pub checked_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub inventory_item_id: i32,
    pub executed_checklist_id: i32,
    pub checked_by: i32,
    pub result_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::executed_checklists::Entity",
        from = "Column::ExecutedChecklistId",
        to = "super::executed_checklists::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ExecutedChecklists,
    #[sea_orm(has_many = "super::inventory_item_check_steps::Entity")]
    InventoryItemCheckSteps,
    #[sea_orm(
        belongs_to = "super::inventory_items::Entity",
        from = "Column::InventoryItemId",
        to = "super::inventory_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    InventoryItems,
    #[sea_orm(
        belongs_to = "super::results::Entity",
        from = "Column::ResultId",
        to = "super::results::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Results,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CheckedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::executed_checklists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExecutedChecklists.def()
    }
}

impl Related<super::inventory_item_check_steps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemCheckSteps.def()
    }
}

impl Related<super::inventory_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItems.def()
    }
}

impl Related<super::results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Results.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
