//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inventory_item_kinds")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub default_checklist_id: i32,
    pub default_interval_id: i32,
    pub default_expiry_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::checklists::Entity",
        from = "Column::DefaultChecklistId",
        to = "super::checklists::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Checklists,
    #[sea_orm(
        belongs_to = "super::expiries::Entity",
        from = "Column::DefaultExpiryId",
        to = "super::expiries::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Expiries,
    #[sea_orm(
        belongs_to = "super::intervals::Entity",
        from = "Column::DefaultIntervalId",
        to = "super::intervals::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Intervals,
    #[sea_orm(has_many = "super::inventory_items::Entity")]
    InventoryItems,
}

impl Related<super::checklists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Checklists.def()
    }
}

impl Related<super::expiries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Expiries.def()
    }
}

impl Related<super::intervals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Intervals.def()
    }
}

impl Related<super::inventory_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItems.def()
    }
}
