//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inventory_item_check_steps")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub inventory_item_check_id: i32,
    pub executed_checklist_step_id: i32,
    pub result_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::executed_checklist_steps::Entity",
        from = "Column::ExecutedChecklistStepId",
        to = "super::executed_checklist_steps::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ExecutedChecklistSteps,
    #[sea_orm(
        belongs_to = "super::inventory_item_checks::Entity",
        from = "Column::InventoryItemCheckId",
        to = "super::inventory_item_checks::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    InventoryItemChecks,
    #[sea_orm(
        belongs_to = "super::results::Entity",
        from = "Column::ResultId",
        to = "super::results::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Results,
}

impl Related<super::executed_checklist_steps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExecutedChecklistSteps.def()
    }
}

impl Related<super::inventory_item_checks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemChecks.def()
    }
}

impl Related<super::results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Results.def()
    }
}
