//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inventory_items")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub serial_number: Option<String>,
    pub last_checked_at: Option<DateTimeWithTimeZone>,
    pub expiry: Option<DateTimeWithTimeZone>,
    pub inventory_item_kind_id: i32,
    pub checklist_id: i32,
    pub interval_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::checklists::Entity",
        from = "Column::ChecklistId",
        to = "super::checklists::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Checklists,
    #[sea_orm(
        belongs_to = "super::intervals::Entity",
        from = "Column::IntervalId",
        to = "super::intervals::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Intervals,
    #[sea_orm(has_many = "super::inventory_item_checks::Entity")]
    InventoryItemChecks,
    #[sea_orm(
        belongs_to = "super::inventory_item_kinds::Entity",
        from = "Column::InventoryItemKindId",
        to = "super::inventory_item_kinds::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    InventoryItemKinds,
}

impl Related<super::checklists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Checklists.def()
    }
}

impl Related<super::intervals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Intervals.def()
    }
}

impl Related<super::inventory_item_checks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemChecks.def()
    }
}

impl Related<super::inventory_item_kinds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItemKinds.def()
    }
}
